Search.appendIndex(
    [
                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Month",
            "name": "Month",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Month.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Month\u003A\u003Adescription\u0028\u0029",
            "name": "description",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Month.html#method_description"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Month\u003A\u003Aquarter\u0028\u0029",
            "name": "quarter",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Month.html#method_quarter"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Month\u003A\u003AisQuarterEnd\u0028\u0029",
            "name": "isQuarterEnd",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Month.html#method_isQuarterEnd"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Month\u003A\u003Aordered\u0028\u0029",
            "name": "ordered",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Month.html#method_ordered"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Month\u003A\u003AJanuary",
            "name": "January",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Month.html#enumcase_January"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Month\u003A\u003AFebruary",
            "name": "February",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Month.html#enumcase_February"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Month\u003A\u003AMarch",
            "name": "March",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Month.html#enumcase_March"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Month\u003A\u003AApril",
            "name": "April",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Month.html#enumcase_April"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Month\u003A\u003AMay",
            "name": "May",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Month.html#enumcase_May"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Month\u003A\u003AJune",
            "name": "June",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Month.html#enumcase_June"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Month\u003A\u003AJuly",
            "name": "July",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Month.html#enumcase_July"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Month\u003A\u003AAugust",
            "name": "August",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Month.html#enumcase_August"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Month\u003A\u003ASeptember",
            "name": "September",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Month.html#enumcase_September"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Month\u003A\u003AOctober",
            "name": "October",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Month.html#enumcase_October"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Month\u003A\u003ANovember",
            "name": "November",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Month.html#enumcase_November"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Month\u003A\u003ADecember",
            "name": "December",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Month.html#enumcase_December"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Quarter",
            "name": "Quarter",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Quarter.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Quarter\u003A\u003Adescription\u0028\u0029",
            "name": "description",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Quarter.html#method_description"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Quarter\u003A\u003Amonths\u0028\u0029",
            "name": "months",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Quarter.html#method_months"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Quarter\u003A\u003AstartMonth\u0028\u0029",
            "name": "startMonth",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Quarter.html#method_startMonth"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Quarter\u003A\u003AendMonth\u0028\u0029",
            "name": "endMonth",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Quarter.html#method_endMonth"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Quarter\u003A\u003Aincludes\u0028\u0029",
            "name": "includes",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Quarter.html#method_includes"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Quarter\u003A\u003Aordered\u0028\u0029",
            "name": "ordered",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Quarter.html#method_ordered"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Quarter\u003A\u003AfromMonth\u0028\u0029",
            "name": "fromMonth",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Quarter.html#method_fromMonth"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Quarter\u003A\u003AQ1",
            "name": "Q1",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Quarter.html#enumcase_Q1"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Quarter\u003A\u003AQ2",
            "name": "Q2",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Quarter.html#enumcase_Q2"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Quarter\u003A\u003AQ3",
            "name": "Q3",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Quarter.html#enumcase_Q3"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Quarter\u003A\u003AQ4",
            "name": "Q4",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Quarter.html#enumcase_Q4"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Semester",
            "name": "Semester",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Semester.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Semester\u003A\u003Adescription\u0028\u0029",
            "name": "description",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Semester.html#method_description"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Semester\u003A\u003Amonths\u0028\u0029",
            "name": "months",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Semester.html#method_months"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Semester\u003A\u003Aquarters\u0028\u0029",
            "name": "quarters",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Semester.html#method_quarters"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Semester\u003A\u003AstartMonth\u0028\u0029",
            "name": "startMonth",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Semester.html#method_startMonth"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Semester\u003A\u003AendMonth\u0028\u0029",
            "name": "endMonth",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Semester.html#method_endMonth"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Semester\u003A\u003Aincludes\u0028\u0029",
            "name": "includes",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Semester.html#method_includes"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Semester\u003A\u003AfromMonth\u0028\u0029",
            "name": "fromMonth",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Semester.html#method_fromMonth"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Semester\u003A\u003AfromQuarter\u0028\u0029",
            "name": "fromQuarter",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Semester.html#method_fromQuarter"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Semester\u003A\u003AH1",
            "name": "H1",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Semester.html#enumcase_H1"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Semester\u003A\u003AH2",
            "name": "H2",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Semester.html#enumcase_H2"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Weekday",
            "name": "Weekday",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Weekday.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Weekday\u003A\u003Adescription\u0028\u0029",
            "name": "description",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Weekday.html#method_description"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Weekday\u003A\u003AisWeekend\u0028\u0029",
            "name": "isWeekend",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Weekday.html#method_isWeekend"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Weekday\u003A\u003AisWeekday\u0028\u0029",
            "name": "isWeekday",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Weekday.html#method_isWeekday"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Weekday\u003A\u003Aordered\u0028\u0029",
            "name": "ordered",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Weekday.html#method_ordered"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Weekday\u003A\u003AMonday",
            "name": "Monday",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Weekday.html#enumcase_Monday"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Weekday\u003A\u003ATuesday",
            "name": "Tuesday",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Weekday.html#enumcase_Tuesday"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Weekday\u003A\u003AWednesday",
            "name": "Wednesday",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Weekday.html#enumcase_Wednesday"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Weekday\u003A\u003AThursday",
            "name": "Thursday",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Weekday.html#enumcase_Thursday"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Weekday\u003A\u003AFriday",
            "name": "Friday",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Weekday.html#enumcase_Friday"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Weekday\u003A\u003ASaturday",
            "name": "Saturday",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Weekday.html#enumcase_Saturday"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar\\Weekday\u003A\u003ASunday",
            "name": "Sunday",
            "summary": "",
            "url": "classes/FastForward-Enum-Calendar-Weekday.html#enumcase_Sunday"
        },                {
            "fqsen": "\\FastForward\\Enum\\Common\\Priority",
            "name": "Priority",
            "summary": "",
            "url": "classes/FastForward-Enum-Common-Priority.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Common\\Priority\u003A\u003Adescription\u0028\u0029",
            "name": "description",
            "summary": "",
            "url": "classes/FastForward-Enum-Common-Priority.html#method_description"
        },                {
            "fqsen": "\\FastForward\\Enum\\Common\\Priority\u003A\u003Aweight\u0028\u0029",
            "name": "weight",
            "summary": "",
            "url": "classes/FastForward-Enum-Common-Priority.html#method_weight"
        },                {
            "fqsen": "\\FastForward\\Enum\\Common\\Priority\u003A\u003AisHigherThan\u0028\u0029",
            "name": "isHigherThan",
            "summary": "",
            "url": "classes/FastForward-Enum-Common-Priority.html#method_isHigherThan"
        },                {
            "fqsen": "\\FastForward\\Enum\\Common\\Priority\u003A\u003AisLowerThan\u0028\u0029",
            "name": "isLowerThan",
            "summary": "",
            "url": "classes/FastForward-Enum-Common-Priority.html#method_isLowerThan"
        },                {
            "fqsen": "\\FastForward\\Enum\\Common\\Priority\u003A\u003Aordered\u0028\u0029",
            "name": "ordered",
            "summary": "",
            "url": "classes/FastForward-Enum-Common-Priority.html#method_ordered"
        },                {
            "fqsen": "\\FastForward\\Enum\\Common\\Priority\u003A\u003ALow",
            "name": "Low",
            "summary": "",
            "url": "classes/FastForward-Enum-Common-Priority.html#enumcase_Low"
        },                {
            "fqsen": "\\FastForward\\Enum\\Common\\Priority\u003A\u003ANormal",
            "name": "Normal",
            "summary": "",
            "url": "classes/FastForward-Enum-Common-Priority.html#enumcase_Normal"
        },                {
            "fqsen": "\\FastForward\\Enum\\Common\\Priority\u003A\u003AHigh",
            "name": "High",
            "summary": "",
            "url": "classes/FastForward-Enum-Common-Priority.html#enumcase_High"
        },                {
            "fqsen": "\\FastForward\\Enum\\Common\\Priority\u003A\u003ACritical",
            "name": "Critical",
            "summary": "",
            "url": "classes/FastForward-Enum-Common-Priority.html#enumcase_Critical"
        },                {
            "fqsen": "\\FastForward\\Enum\\Common\\Severity",
            "name": "Severity",
            "summary": "",
            "url": "classes/FastForward-Enum-Common-Severity.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Common\\Severity\u003A\u003Adescription\u0028\u0029",
            "name": "description",
            "summary": "",
            "url": "classes/FastForward-Enum-Common-Severity.html#method_description"
        },                {
            "fqsen": "\\FastForward\\Enum\\Common\\Severity\u003A\u003Aweight\u0028\u0029",
            "name": "weight",
            "summary": "",
            "url": "classes/FastForward-Enum-Common-Severity.html#method_weight"
        },                {
            "fqsen": "\\FastForward\\Enum\\Common\\Severity\u003A\u003AisAtLeast\u0028\u0029",
            "name": "isAtLeast",
            "summary": "",
            "url": "classes/FastForward-Enum-Common-Severity.html#method_isAtLeast"
        },                {
            "fqsen": "\\FastForward\\Enum\\Common\\Severity\u003A\u003Aordered\u0028\u0029",
            "name": "ordered",
            "summary": "",
            "url": "classes/FastForward-Enum-Common-Severity.html#method_ordered"
        },                {
            "fqsen": "\\FastForward\\Enum\\Common\\Severity\u003A\u003ADebug",
            "name": "Debug",
            "summary": "",
            "url": "classes/FastForward-Enum-Common-Severity.html#enumcase_Debug"
        },                {
            "fqsen": "\\FastForward\\Enum\\Common\\Severity\u003A\u003AInfo",
            "name": "Info",
            "summary": "",
            "url": "classes/FastForward-Enum-Common-Severity.html#enumcase_Info"
        },                {
            "fqsen": "\\FastForward\\Enum\\Common\\Severity\u003A\u003ANotice",
            "name": "Notice",
            "summary": "",
            "url": "classes/FastForward-Enum-Common-Severity.html#enumcase_Notice"
        },                {
            "fqsen": "\\FastForward\\Enum\\Common\\Severity\u003A\u003AWarning",
            "name": "Warning",
            "summary": "",
            "url": "classes/FastForward-Enum-Common-Severity.html#enumcase_Warning"
        },                {
            "fqsen": "\\FastForward\\Enum\\Common\\Severity\u003A\u003AError",
            "name": "Error",
            "summary": "",
            "url": "classes/FastForward-Enum-Common-Severity.html#enumcase_Error"
        },                {
            "fqsen": "\\FastForward\\Enum\\Common\\Severity\u003A\u003ACritical",
            "name": "Critical",
            "summary": "",
            "url": "classes/FastForward-Enum-Common-Severity.html#enumcase_Critical"
        },                {
            "fqsen": "\\FastForward\\Enum\\Comparison\\ComparisonOperator",
            "name": "ComparisonOperator",
            "summary": "",
            "url": "classes/FastForward-Enum-Comparison-ComparisonOperator.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Comparison\\ComparisonOperator\u003A\u003Adescription\u0028\u0029",
            "name": "description",
            "summary": "",
            "url": "classes/FastForward-Enum-Comparison-ComparisonOperator.html#method_description"
        },                {
            "fqsen": "\\FastForward\\Enum\\Comparison\\ComparisonOperator\u003A\u003Asymbol\u0028\u0029",
            "name": "symbol",
            "summary": "",
            "url": "classes/FastForward-Enum-Comparison-ComparisonOperator.html#method_symbol"
        },                {
            "fqsen": "\\FastForward\\Enum\\Comparison\\ComparisonOperator\u003A\u003AisSetOperator\u0028\u0029",
            "name": "isSetOperator",
            "summary": "",
            "url": "classes/FastForward-Enum-Comparison-ComparisonOperator.html#method_isSetOperator"
        },                {
            "fqsen": "\\FastForward\\Enum\\Comparison\\ComparisonOperator\u003A\u003Acompare\u0028\u0029",
            "name": "compare",
            "summary": "",
            "url": "classes/FastForward-Enum-Comparison-ComparisonOperator.html#method_compare"
        },                {
            "fqsen": "\\FastForward\\Enum\\Comparison\\ComparisonOperator\u003A\u003Anegate\u0028\u0029",
            "name": "negate",
            "summary": "",
            "url": "classes/FastForward-Enum-Comparison-ComparisonOperator.html#method_negate"
        },                {
            "fqsen": "\\FastForward\\Enum\\Comparison\\ComparisonOperator\u003A\u003AcandidateSet\u0028\u0029",
            "name": "candidateSet",
            "summary": "",
            "url": "classes/FastForward-Enum-Comparison-ComparisonOperator.html#method_candidateSet"
        },                {
            "fqsen": "\\FastForward\\Enum\\Comparison\\ComparisonOperator\u003A\u003AEqual",
            "name": "Equal",
            "summary": "",
            "url": "classes/FastForward-Enum-Comparison-ComparisonOperator.html#enumcase_Equal"
        },                {
            "fqsen": "\\FastForward\\Enum\\Comparison\\ComparisonOperator\u003A\u003ANotEqual",
            "name": "NotEqual",
            "summary": "",
            "url": "classes/FastForward-Enum-Comparison-ComparisonOperator.html#enumcase_NotEqual"
        },                {
            "fqsen": "\\FastForward\\Enum\\Comparison\\ComparisonOperator\u003A\u003AGreaterThan",
            "name": "GreaterThan",
            "summary": "",
            "url": "classes/FastForward-Enum-Comparison-ComparisonOperator.html#enumcase_GreaterThan"
        },                {
            "fqsen": "\\FastForward\\Enum\\Comparison\\ComparisonOperator\u003A\u003AGreaterThanOrEqual",
            "name": "GreaterThanOrEqual",
            "summary": "",
            "url": "classes/FastForward-Enum-Comparison-ComparisonOperator.html#enumcase_GreaterThanOrEqual"
        },                {
            "fqsen": "\\FastForward\\Enum\\Comparison\\ComparisonOperator\u003A\u003ALessThan",
            "name": "LessThan",
            "summary": "",
            "url": "classes/FastForward-Enum-Comparison-ComparisonOperator.html#enumcase_LessThan"
        },                {
            "fqsen": "\\FastForward\\Enum\\Comparison\\ComparisonOperator\u003A\u003ALessThanOrEqual",
            "name": "LessThanOrEqual",
            "summary": "",
            "url": "classes/FastForward-Enum-Comparison-ComparisonOperator.html#enumcase_LessThanOrEqual"
        },                {
            "fqsen": "\\FastForward\\Enum\\Comparison\\ComparisonOperator\u003A\u003AIn",
            "name": "In",
            "summary": "",
            "url": "classes/FastForward-Enum-Comparison-ComparisonOperator.html#enumcase_In"
        },                {
            "fqsen": "\\FastForward\\Enum\\Comparison\\ComparisonOperator\u003A\u003ANotIn",
            "name": "NotIn",
            "summary": "",
            "url": "classes/FastForward-Enum-Comparison-ComparisonOperator.html#enumcase_NotIn"
        },                {
            "fqsen": "\\FastForward\\Enum\\Container\\ServiceLifetime",
            "name": "ServiceLifetime",
            "summary": "",
            "url": "classes/FastForward-Enum-Container-ServiceLifetime.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Container\\ServiceLifetime\u003A\u003Adescription\u0028\u0029",
            "name": "description",
            "summary": "",
            "url": "classes/FastForward-Enum-Container-ServiceLifetime.html#method_description"
        },                {
            "fqsen": "\\FastForward\\Enum\\Container\\ServiceLifetime\u003A\u003AisReusable\u0028\u0029",
            "name": "isReusable",
            "summary": "",
            "url": "classes/FastForward-Enum-Container-ServiceLifetime.html#method_isReusable"
        },                {
            "fqsen": "\\FastForward\\Enum\\Container\\ServiceLifetime\u003A\u003ASingleton",
            "name": "Singleton",
            "summary": "",
            "url": "classes/FastForward-Enum-Container-ServiceLifetime.html#enumcase_Singleton"
        },                {
            "fqsen": "\\FastForward\\Enum\\Container\\ServiceLifetime\u003A\u003ATransient",
            "name": "Transient",
            "summary": "",
            "url": "classes/FastForward-Enum-Container-ServiceLifetime.html#enumcase_Transient"
        },                {
            "fqsen": "\\FastForward\\Enum\\DateTime\\IntervalUnit",
            "name": "IntervalUnit",
            "summary": "",
            "url": "classes/FastForward-Enum-DateTime-IntervalUnit.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\DateTime\\IntervalUnit\u003A\u003Adescription\u0028\u0029",
            "name": "description",
            "summary": "",
            "url": "classes/FastForward-Enum-DateTime-IntervalUnit.html#method_description"
        },                {
            "fqsen": "\\FastForward\\Enum\\DateTime\\IntervalUnit\u003A\u003AshortLabel\u0028\u0029",
            "name": "shortLabel",
            "summary": "",
            "url": "classes/FastForward-Enum-DateTime-IntervalUnit.html#method_shortLabel"
        },                {
            "fqsen": "\\FastForward\\Enum\\DateTime\\IntervalUnit\u003A\u003Aseconds\u0028\u0029",
            "name": "seconds",
            "summary": "",
            "url": "classes/FastForward-Enum-DateTime-IntervalUnit.html#method_seconds"
        },                {
            "fqsen": "\\FastForward\\Enum\\DateTime\\IntervalUnit\u003A\u003AisCalendarAware\u0028\u0029",
            "name": "isCalendarAware",
            "summary": "",
            "url": "classes/FastForward-Enum-DateTime-IntervalUnit.html#method_isCalendarAware"
        },                {
            "fqsen": "\\FastForward\\Enum\\DateTime\\IntervalUnit\u003A\u003ASecond",
            "name": "Second",
            "summary": "",
            "url": "classes/FastForward-Enum-DateTime-IntervalUnit.html#enumcase_Second"
        },                {
            "fqsen": "\\FastForward\\Enum\\DateTime\\IntervalUnit\u003A\u003AMinute",
            "name": "Minute",
            "summary": "",
            "url": "classes/FastForward-Enum-DateTime-IntervalUnit.html#enumcase_Minute"
        },                {
            "fqsen": "\\FastForward\\Enum\\DateTime\\IntervalUnit\u003A\u003AHour",
            "name": "Hour",
            "summary": "",
            "url": "classes/FastForward-Enum-DateTime-IntervalUnit.html#enumcase_Hour"
        },                {
            "fqsen": "\\FastForward\\Enum\\DateTime\\IntervalUnit\u003A\u003ADay",
            "name": "Day",
            "summary": "",
            "url": "classes/FastForward-Enum-DateTime-IntervalUnit.html#enumcase_Day"
        },                {
            "fqsen": "\\FastForward\\Enum\\DateTime\\IntervalUnit\u003A\u003AWeek",
            "name": "Week",
            "summary": "",
            "url": "classes/FastForward-Enum-DateTime-IntervalUnit.html#enumcase_Week"
        },                {
            "fqsen": "\\FastForward\\Enum\\DateTime\\IntervalUnit\u003A\u003AMonth",
            "name": "Month",
            "summary": "",
            "url": "classes/FastForward-Enum-DateTime-IntervalUnit.html#enumcase_Month"
        },                {
            "fqsen": "\\FastForward\\Enum\\DateTime\\IntervalUnit\u003A\u003AYear",
            "name": "Year",
            "summary": "",
            "url": "classes/FastForward-Enum-DateTime-IntervalUnit.html#enumcase_Year"
        },                {
            "fqsen": "\\FastForward\\Enum\\DescribedEnumInterface",
            "name": "DescribedEnumInterface",
            "summary": "",
            "url": "classes/FastForward-Enum-DescribedEnumInterface.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\DescribedEnumInterface\u003A\u003Adescription\u0028\u0029",
            "name": "description",
            "summary": "",
            "url": "classes/FastForward-Enum-DescribedEnumInterface.html#method_description"
        },                {
            "fqsen": "\\FastForward\\Enum\\Event\\DispatchMode",
            "name": "DispatchMode",
            "summary": "",
            "url": "classes/FastForward-Enum-Event-DispatchMode.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Event\\DispatchMode\u003A\u003Adescription\u0028\u0029",
            "name": "description",
            "summary": "",
            "url": "classes/FastForward-Enum-Event-DispatchMode.html#method_description"
        },                {
            "fqsen": "\\FastForward\\Enum\\Event\\DispatchMode\u003A\u003AisSync\u0028\u0029",
            "name": "isSync",
            "summary": "",
            "url": "classes/FastForward-Enum-Event-DispatchMode.html#method_isSync"
        },                {
            "fqsen": "\\FastForward\\Enum\\Event\\DispatchMode\u003A\u003AisAsync\u0028\u0029",
            "name": "isAsync",
            "summary": "",
            "url": "classes/FastForward-Enum-Event-DispatchMode.html#method_isAsync"
        },                {
            "fqsen": "\\FastForward\\Enum\\Event\\DispatchMode\u003A\u003ASync",
            "name": "Sync",
            "summary": "",
            "url": "classes/FastForward-Enum-Event-DispatchMode.html#enumcase_Sync"
        },                {
            "fqsen": "\\FastForward\\Enum\\Event\\DispatchMode\u003A\u003AAsync",
            "name": "Async",
            "summary": "",
            "url": "classes/FastForward-Enum-Event-DispatchMode.html#enumcase_Async"
        },                {
            "fqsen": "\\FastForward\\Enum\\Helper\\EnumHelper",
            "name": "EnumHelper",
            "summary": "",
            "url": "classes/FastForward-Enum-Helper-EnumHelper.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Helper\\EnumHelper\u003A\u003Acases\u0028\u0029",
            "name": "cases",
            "summary": "",
            "url": "classes/FastForward-Enum-Helper-EnumHelper.html#method_cases"
        },                {
            "fqsen": "\\FastForward\\Enum\\Helper\\EnumHelper\u003A\u003Anames\u0028\u0029",
            "name": "names",
            "summary": "",
            "url": "classes/FastForward-Enum-Helper-EnumHelper.html#method_names"
        },                {
            "fqsen": "\\FastForward\\Enum\\Helper\\EnumHelper\u003A\u003Avalues\u0028\u0029",
            "name": "values",
            "summary": "",
            "url": "classes/FastForward-Enum-Helper-EnumHelper.html#method_values"
        },                {
            "fqsen": "\\FastForward\\Enum\\Helper\\EnumHelper\u003A\u003AnameMap\u0028\u0029",
            "name": "nameMap",
            "summary": "",
            "url": "classes/FastForward-Enum-Helper-EnumHelper.html#method_nameMap"
        },                {
            "fqsen": "\\FastForward\\Enum\\Helper\\EnumHelper\u003A\u003AvalueMap\u0028\u0029",
            "name": "valueMap",
            "summary": "",
            "url": "classes/FastForward-Enum-Helper-EnumHelper.html#method_valueMap"
        },                {
            "fqsen": "\\FastForward\\Enum\\Helper\\EnumHelper\u003A\u003Aoptions\u0028\u0029",
            "name": "options",
            "summary": "",
            "url": "classes/FastForward-Enum-Helper-EnumHelper.html#method_options"
        },                {
            "fqsen": "\\FastForward\\Enum\\Helper\\EnumHelper\u003A\u003AhasName\u0028\u0029",
            "name": "hasName",
            "summary": "",
            "url": "classes/FastForward-Enum-Helper-EnumHelper.html#method_hasName"
        },                {
            "fqsen": "\\FastForward\\Enum\\Helper\\EnumHelper\u003A\u003AhasValue\u0028\u0029",
            "name": "hasValue",
            "summary": "",
            "url": "classes/FastForward-Enum-Helper-EnumHelper.html#method_hasValue"
        },                {
            "fqsen": "\\FastForward\\Enum\\Helper\\EnumHelper\u003A\u003AtryFromName\u0028\u0029",
            "name": "tryFromName",
            "summary": "",
            "url": "classes/FastForward-Enum-Helper-EnumHelper.html#method_tryFromName"
        },                {
            "fqsen": "\\FastForward\\Enum\\Helper\\EnumHelper\u003A\u003AfromName\u0028\u0029",
            "name": "fromName",
            "summary": "",
            "url": "classes/FastForward-Enum-Helper-EnumHelper.html#method_fromName"
        },                {
            "fqsen": "\\FastForward\\Enum\\Helper\\EnumHelper\u003A\u003Alabels\u0028\u0029",
            "name": "labels",
            "summary": "",
            "url": "classes/FastForward-Enum-Helper-EnumHelper.html#method_labels"
        },                {
            "fqsen": "\\FastForward\\Enum\\Helper\\EnumHelper\u003A\u003AlabelMap\u0028\u0029",
            "name": "labelMap",
            "summary": "",
            "url": "classes/FastForward-Enum-Helper-EnumHelper.html#method_labelMap"
        },                {
            "fqsen": "\\FastForward\\Enum\\Helper\\EnumHelper\u003A\u003AunitEnumClass\u0028\u0029",
            "name": "unitEnumClass",
            "summary": "",
            "url": "classes/FastForward-Enum-Helper-EnumHelper.html#method_unitEnumClass"
        },                {
            "fqsen": "\\FastForward\\Enum\\Helper\\EnumHelper\u003A\u003AbackedEnumClass\u0028\u0029",
            "name": "backedEnumClass",
            "summary": "",
            "url": "classes/FastForward-Enum-Helper-EnumHelper.html#method_backedEnumClass"
        },                {
            "fqsen": "\\FastForward\\Enum\\Helper\\EnumHelper\u003A\u003AlabeledEnumClass\u0028\u0029",
            "name": "labeledEnumClass",
            "summary": "",
            "url": "classes/FastForward-Enum-Helper-EnumHelper.html#method_labeledEnumClass"
        },                {
            "fqsen": "\\FastForward\\Enum\\Http\\Scheme",
            "name": "Scheme",
            "summary": "",
            "url": "classes/FastForward-Enum-Http-Scheme.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Http\\Scheme\u003A\u003Adescription\u0028\u0029",
            "name": "description",
            "summary": "",
            "url": "classes/FastForward-Enum-Http-Scheme.html#method_description"
        },                {
            "fqsen": "\\FastForward\\Enum\\Http\\Scheme\u003A\u003AdefaultPort\u0028\u0029",
            "name": "defaultPort",
            "summary": "",
            "url": "classes/FastForward-Enum-Http-Scheme.html#method_defaultPort"
        },                {
            "fqsen": "\\FastForward\\Enum\\Http\\Scheme\u003A\u003AisSecure\u0028\u0029",
            "name": "isSecure",
            "summary": "",
            "url": "classes/FastForward-Enum-Http-Scheme.html#method_isSecure"
        },                {
            "fqsen": "\\FastForward\\Enum\\Http\\Scheme\u003A\u003AHttp",
            "name": "Http",
            "summary": "",
            "url": "classes/FastForward-Enum-Http-Scheme.html#enumcase_Http"
        },                {
            "fqsen": "\\FastForward\\Enum\\Http\\Scheme\u003A\u003AHttps",
            "name": "Https",
            "summary": "",
            "url": "classes/FastForward-Enum-Http-Scheme.html#enumcase_Https"
        },                {
            "fqsen": "\\FastForward\\Enum\\LabeledEnumInterface",
            "name": "LabeledEnumInterface",
            "summary": "",
            "url": "classes/FastForward-Enum-LabeledEnumInterface.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\LabeledEnumInterface\u003A\u003Alabel\u0028\u0029",
            "name": "label",
            "summary": "",
            "url": "classes/FastForward-Enum-LabeledEnumInterface.html#method_label"
        },                {
            "fqsen": "\\FastForward\\Enum\\Logger\\LogLevel",
            "name": "LogLevel",
            "summary": "",
            "url": "classes/FastForward-Enum-Logger-LogLevel.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Logger\\LogLevel\u003A\u003Adescription\u0028\u0029",
            "name": "description",
            "summary": "",
            "url": "classes/FastForward-Enum-Logger-LogLevel.html#method_description"
        },                {
            "fqsen": "\\FastForward\\Enum\\Logger\\LogLevel\u003A\u003Aweight\u0028\u0029",
            "name": "weight",
            "summary": "",
            "url": "classes/FastForward-Enum-Logger-LogLevel.html#method_weight"
        },                {
            "fqsen": "\\FastForward\\Enum\\Logger\\LogLevel\u003A\u003AisAtLeast\u0028\u0029",
            "name": "isAtLeast",
            "summary": "",
            "url": "classes/FastForward-Enum-Logger-LogLevel.html#method_isAtLeast"
        },                {
            "fqsen": "\\FastForward\\Enum\\Logger\\LogLevel\u003A\u003Aordered\u0028\u0029",
            "name": "ordered",
            "summary": "",
            "url": "classes/FastForward-Enum-Logger-LogLevel.html#method_ordered"
        },                {
            "fqsen": "\\FastForward\\Enum\\Logger\\LogLevel\u003A\u003AEmergency",
            "name": "Emergency",
            "summary": "",
            "url": "classes/FastForward-Enum-Logger-LogLevel.html#enumcase_Emergency"
        },                {
            "fqsen": "\\FastForward\\Enum\\Logger\\LogLevel\u003A\u003AAlert",
            "name": "Alert",
            "summary": "",
            "url": "classes/FastForward-Enum-Logger-LogLevel.html#enumcase_Alert"
        },                {
            "fqsen": "\\FastForward\\Enum\\Logger\\LogLevel\u003A\u003ACritical",
            "name": "Critical",
            "summary": "",
            "url": "classes/FastForward-Enum-Logger-LogLevel.html#enumcase_Critical"
        },                {
            "fqsen": "\\FastForward\\Enum\\Logger\\LogLevel\u003A\u003AError",
            "name": "Error",
            "summary": "",
            "url": "classes/FastForward-Enum-Logger-LogLevel.html#enumcase_Error"
        },                {
            "fqsen": "\\FastForward\\Enum\\Logger\\LogLevel\u003A\u003AWarning",
            "name": "Warning",
            "summary": "",
            "url": "classes/FastForward-Enum-Logger-LogLevel.html#enumcase_Warning"
        },                {
            "fqsen": "\\FastForward\\Enum\\Logger\\LogLevel\u003A\u003ANotice",
            "name": "Notice",
            "summary": "",
            "url": "classes/FastForward-Enum-Logger-LogLevel.html#enumcase_Notice"
        },                {
            "fqsen": "\\FastForward\\Enum\\Logger\\LogLevel\u003A\u003AInfo",
            "name": "Info",
            "summary": "",
            "url": "classes/FastForward-Enum-Logger-LogLevel.html#enumcase_Info"
        },                {
            "fqsen": "\\FastForward\\Enum\\Logger\\LogLevel\u003A\u003ADebug",
            "name": "Debug",
            "summary": "",
            "url": "classes/FastForward-Enum-Logger-LogLevel.html#enumcase_Debug"
        },                {
            "fqsen": "\\FastForward\\Enum\\Outcome\\Result",
            "name": "Result",
            "summary": "",
            "url": "classes/FastForward-Enum-Outcome-Result.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Outcome\\Result\u003A\u003Adescription\u0028\u0029",
            "name": "description",
            "summary": "",
            "url": "classes/FastForward-Enum-Outcome-Result.html#method_description"
        },                {
            "fqsen": "\\FastForward\\Enum\\Outcome\\Result\u003A\u003AisSuccessful\u0028\u0029",
            "name": "isSuccessful",
            "summary": "",
            "url": "classes/FastForward-Enum-Outcome-Result.html#method_isSuccessful"
        },                {
            "fqsen": "\\FastForward\\Enum\\Outcome\\Result\u003A\u003AisCompleteSuccess\u0028\u0029",
            "name": "isCompleteSuccess",
            "summary": "",
            "url": "classes/FastForward-Enum-Outcome-Result.html#method_isCompleteSuccess"
        },                {
            "fqsen": "\\FastForward\\Enum\\Outcome\\Result\u003A\u003AisFailure\u0028\u0029",
            "name": "isFailure",
            "summary": "",
            "url": "classes/FastForward-Enum-Outcome-Result.html#method_isFailure"
        },                {
            "fqsen": "\\FastForward\\Enum\\Outcome\\Result\u003A\u003ASuccess",
            "name": "Success",
            "summary": "",
            "url": "classes/FastForward-Enum-Outcome-Result.html#enumcase_Success"
        },                {
            "fqsen": "\\FastForward\\Enum\\Outcome\\Result\u003A\u003APartial",
            "name": "Partial",
            "summary": "",
            "url": "classes/FastForward-Enum-Outcome-Result.html#enumcase_Partial"
        },                {
            "fqsen": "\\FastForward\\Enum\\Outcome\\Result\u003A\u003AFailure",
            "name": "Failure",
            "summary": "",
            "url": "classes/FastForward-Enum-Outcome-Result.html#enumcase_Failure"
        },                {
            "fqsen": "\\FastForward\\Enum\\Pipeline\\FailureMode",
            "name": "FailureMode",
            "summary": "",
            "url": "classes/FastForward-Enum-Pipeline-FailureMode.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Pipeline\\FailureMode\u003A\u003Adescription\u0028\u0029",
            "name": "description",
            "summary": "",
            "url": "classes/FastForward-Enum-Pipeline-FailureMode.html#method_description"
        },                {
            "fqsen": "\\FastForward\\Enum\\Pipeline\\FailureMode\u003A\u003AstopsOnFailure\u0028\u0029",
            "name": "stopsOnFailure",
            "summary": "",
            "url": "classes/FastForward-Enum-Pipeline-FailureMode.html#method_stopsOnFailure"
        },                {
            "fqsen": "\\FastForward\\Enum\\Pipeline\\FailureMode\u003A\u003AStopOnFailure",
            "name": "StopOnFailure",
            "summary": "",
            "url": "classes/FastForward-Enum-Pipeline-FailureMode.html#enumcase_StopOnFailure"
        },                {
            "fqsen": "\\FastForward\\Enum\\Pipeline\\FailureMode\u003A\u003AContinueOnFailure",
            "name": "ContinueOnFailure",
            "summary": "",
            "url": "classes/FastForward-Enum-Pipeline-FailureMode.html#enumcase_ContinueOnFailure"
        },                {
            "fqsen": "\\FastForward\\Enum\\Process\\SignalBehavior",
            "name": "SignalBehavior",
            "summary": "",
            "url": "classes/FastForward-Enum-Process-SignalBehavior.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Process\\SignalBehavior\u003A\u003Adescription\u0028\u0029",
            "name": "description",
            "summary": "",
            "url": "classes/FastForward-Enum-Process-SignalBehavior.html#method_description"
        },                {
            "fqsen": "\\FastForward\\Enum\\Process\\SignalBehavior\u003A\u003AisTerminalControl\u0028\u0029",
            "name": "isTerminalControl",
            "summary": "",
            "url": "classes/FastForward-Enum-Process-SignalBehavior.html#method_isTerminalControl"
        },                {
            "fqsen": "\\FastForward\\Enum\\Process\\SignalBehavior\u003A\u003AIgnore",
            "name": "Ignore",
            "summary": "",
            "url": "classes/FastForward-Enum-Process-SignalBehavior.html#enumcase_Ignore"
        },                {
            "fqsen": "\\FastForward\\Enum\\Process\\SignalBehavior\u003A\u003AHandle",
            "name": "Handle",
            "summary": "",
            "url": "classes/FastForward-Enum-Process-SignalBehavior.html#enumcase_Handle"
        },                {
            "fqsen": "\\FastForward\\Enum\\Process\\SignalBehavior\u003A\u003APropagate",
            "name": "Propagate",
            "summary": "",
            "url": "classes/FastForward-Enum-Process-SignalBehavior.html#enumcase_Propagate"
        },                {
            "fqsen": "\\FastForward\\Enum\\ReversibleInterface",
            "name": "ReversibleInterface",
            "summary": "",
            "url": "classes/FastForward-Enum-ReversibleInterface.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\ReversibleInterface\u003A\u003Areverse\u0028\u0029",
            "name": "reverse",
            "summary": "",
            "url": "classes/FastForward-Enum-ReversibleInterface.html#method_reverse"
        },                {
            "fqsen": "\\FastForward\\Enum\\Runtime\\Environment",
            "name": "Environment",
            "summary": "",
            "url": "classes/FastForward-Enum-Runtime-Environment.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Runtime\\Environment\u003A\u003Adescription\u0028\u0029",
            "name": "description",
            "summary": "",
            "url": "classes/FastForward-Enum-Runtime-Environment.html#method_description"
        },                {
            "fqsen": "\\FastForward\\Enum\\Runtime\\Environment\u003A\u003AisProduction\u0028\u0029",
            "name": "isProduction",
            "summary": "",
            "url": "classes/FastForward-Enum-Runtime-Environment.html#method_isProduction"
        },                {
            "fqsen": "\\FastForward\\Enum\\Runtime\\Environment\u003A\u003AisPreProduction\u0028\u0029",
            "name": "isPreProduction",
            "summary": "",
            "url": "classes/FastForward-Enum-Runtime-Environment.html#method_isPreProduction"
        },                {
            "fqsen": "\\FastForward\\Enum\\Runtime\\Environment\u003A\u003AisDebugFriendly\u0028\u0029",
            "name": "isDebugFriendly",
            "summary": "",
            "url": "classes/FastForward-Enum-Runtime-Environment.html#method_isDebugFriendly"
        },                {
            "fqsen": "\\FastForward\\Enum\\Runtime\\Environment\u003A\u003ADevelopment",
            "name": "Development",
            "summary": "",
            "url": "classes/FastForward-Enum-Runtime-Environment.html#enumcase_Development"
        },                {
            "fqsen": "\\FastForward\\Enum\\Runtime\\Environment\u003A\u003ATesting",
            "name": "Testing",
            "summary": "",
            "url": "classes/FastForward-Enum-Runtime-Environment.html#enumcase_Testing"
        },                {
            "fqsen": "\\FastForward\\Enum\\Runtime\\Environment\u003A\u003AStaging",
            "name": "Staging",
            "summary": "",
            "url": "classes/FastForward-Enum-Runtime-Environment.html#enumcase_Staging"
        },                {
            "fqsen": "\\FastForward\\Enum\\Runtime\\Environment\u003A\u003AProduction",
            "name": "Production",
            "summary": "",
            "url": "classes/FastForward-Enum-Runtime-Environment.html#enumcase_Production"
        },                {
            "fqsen": "\\FastForward\\Enum\\Sort\\CaseSensitivity",
            "name": "CaseSensitivity",
            "summary": "",
            "url": "classes/FastForward-Enum-Sort-CaseSensitivity.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Sort\\CaseSensitivity\u003A\u003Areverse\u0028\u0029",
            "name": "reverse",
            "summary": "",
            "url": "classes/FastForward-Enum-Sort-CaseSensitivity.html#method_reverse"
        },                {
            "fqsen": "\\FastForward\\Enum\\Sort\\CaseSensitivity\u003A\u003AisSensitive\u0028\u0029",
            "name": "isSensitive",
            "summary": "",
            "url": "classes/FastForward-Enum-Sort-CaseSensitivity.html#method_isSensitive"
        },                {
            "fqsen": "\\FastForward\\Enum\\Sort\\CaseSensitivity\u003A\u003AisInsensitive\u0028\u0029",
            "name": "isInsensitive",
            "summary": "",
            "url": "classes/FastForward-Enum-Sort-CaseSensitivity.html#method_isInsensitive"
        },                {
            "fqsen": "\\FastForward\\Enum\\Sort\\CaseSensitivity\u003A\u003Anormalize\u0028\u0029",
            "name": "normalize",
            "summary": "",
            "url": "classes/FastForward-Enum-Sort-CaseSensitivity.html#method_normalize"
        },                {
            "fqsen": "\\FastForward\\Enum\\Sort\\CaseSensitivity\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/FastForward-Enum-Sort-CaseSensitivity.html#method_equals"
        },                {
            "fqsen": "\\FastForward\\Enum\\Sort\\CaseSensitivity\u003A\u003ASensitive",
            "name": "Sensitive",
            "summary": "",
            "url": "classes/FastForward-Enum-Sort-CaseSensitivity.html#enumcase_Sensitive"
        },                {
            "fqsen": "\\FastForward\\Enum\\Sort\\CaseSensitivity\u003A\u003AInsensitive",
            "name": "Insensitive",
            "summary": "",
            "url": "classes/FastForward-Enum-Sort-CaseSensitivity.html#enumcase_Insensitive"
        },                {
            "fqsen": "\\FastForward\\Enum\\Sort\\ComparisonResult",
            "name": "ComparisonResult",
            "summary": "",
            "url": "classes/FastForward-Enum-Sort-ComparisonResult.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Sort\\ComparisonResult\u003A\u003AfromComparisonResult\u0028\u0029",
            "name": "fromComparisonResult",
            "summary": "",
            "url": "classes/FastForward-Enum-Sort-ComparisonResult.html#method_fromComparisonResult"
        },                {
            "fqsen": "\\FastForward\\Enum\\Sort\\ComparisonResult\u003A\u003AtoComparisonResult\u0028\u0029",
            "name": "toComparisonResult",
            "summary": "",
            "url": "classes/FastForward-Enum-Sort-ComparisonResult.html#method_toComparisonResult"
        },                {
            "fqsen": "\\FastForward\\Enum\\Sort\\ComparisonResult\u003A\u003Areverse\u0028\u0029",
            "name": "reverse",
            "summary": "",
            "url": "classes/FastForward-Enum-Sort-ComparisonResult.html#method_reverse"
        },                {
            "fqsen": "\\FastForward\\Enum\\Sort\\ComparisonResult\u003A\u003AisComparable\u0028\u0029",
            "name": "isComparable",
            "summary": "",
            "url": "classes/FastForward-Enum-Sort-ComparisonResult.html#method_isComparable"
        },                {
            "fqsen": "\\FastForward\\Enum\\Sort\\ComparisonResult\u003A\u003ALeftGreater",
            "name": "LeftGreater",
            "summary": "",
            "url": "classes/FastForward-Enum-Sort-ComparisonResult.html#enumcase_LeftGreater"
        },                {
            "fqsen": "\\FastForward\\Enum\\Sort\\ComparisonResult\u003A\u003ARightGreater",
            "name": "RightGreater",
            "summary": "",
            "url": "classes/FastForward-Enum-Sort-ComparisonResult.html#enumcase_RightGreater"
        },                {
            "fqsen": "\\FastForward\\Enum\\Sort\\ComparisonResult\u003A\u003AEqual",
            "name": "Equal",
            "summary": "",
            "url": "classes/FastForward-Enum-Sort-ComparisonResult.html#enumcase_Equal"
        },                {
            "fqsen": "\\FastForward\\Enum\\Sort\\ComparisonResult\u003A\u003AUncomparable",
            "name": "Uncomparable",
            "summary": "",
            "url": "classes/FastForward-Enum-Sort-ComparisonResult.html#enumcase_Uncomparable"
        },                {
            "fqsen": "\\FastForward\\Enum\\Sort\\NullsPosition",
            "name": "NullsPosition",
            "summary": "",
            "url": "classes/FastForward-Enum-Sort-NullsPosition.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Sort\\NullsPosition\u003A\u003Areverse\u0028\u0029",
            "name": "reverse",
            "summary": "",
            "url": "classes/FastForward-Enum-Sort-NullsPosition.html#method_reverse"
        },                {
            "fqsen": "\\FastForward\\Enum\\Sort\\NullsPosition\u003A\u003AisFirst\u0028\u0029",
            "name": "isFirst",
            "summary": "",
            "url": "classes/FastForward-Enum-Sort-NullsPosition.html#method_isFirst"
        },                {
            "fqsen": "\\FastForward\\Enum\\Sort\\NullsPosition\u003A\u003AisLast\u0028\u0029",
            "name": "isLast",
            "summary": "",
            "url": "classes/FastForward-Enum-Sort-NullsPosition.html#method_isLast"
        },                {
            "fqsen": "\\FastForward\\Enum\\Sort\\NullsPosition\u003A\u003AcompareNullability\u0028\u0029",
            "name": "compareNullability",
            "summary": "",
            "url": "classes/FastForward-Enum-Sort-NullsPosition.html#method_compareNullability"
        },                {
            "fqsen": "\\FastForward\\Enum\\Sort\\NullsPosition\u003A\u003AFirst",
            "name": "First",
            "summary": "",
            "url": "classes/FastForward-Enum-Sort-NullsPosition.html#enumcase_First"
        },                {
            "fqsen": "\\FastForward\\Enum\\Sort\\NullsPosition\u003A\u003ALast",
            "name": "Last",
            "summary": "",
            "url": "classes/FastForward-Enum-Sort-NullsPosition.html#enumcase_Last"
        },                {
            "fqsen": "\\FastForward\\Enum\\Sort\\SortDirection",
            "name": "SortDirection",
            "summary": "",
            "url": "classes/FastForward-Enum-Sort-SortDirection.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Sort\\SortDirection\u003A\u003Areverse\u0028\u0029",
            "name": "reverse",
            "summary": "",
            "url": "classes/FastForward-Enum-Sort-SortDirection.html#method_reverse"
        },                {
            "fqsen": "\\FastForward\\Enum\\Sort\\SortDirection\u003A\u003AisAscending\u0028\u0029",
            "name": "isAscending",
            "summary": "",
            "url": "classes/FastForward-Enum-Sort-SortDirection.html#method_isAscending"
        },                {
            "fqsen": "\\FastForward\\Enum\\Sort\\SortDirection\u003A\u003AisDescending\u0028\u0029",
            "name": "isDescending",
            "summary": "",
            "url": "classes/FastForward-Enum-Sort-SortDirection.html#method_isDescending"
        },                {
            "fqsen": "\\FastForward\\Enum\\Sort\\SortDirection\u003A\u003Afactor\u0028\u0029",
            "name": "factor",
            "summary": "",
            "url": "classes/FastForward-Enum-Sort-SortDirection.html#method_factor"
        },                {
            "fqsen": "\\FastForward\\Enum\\Sort\\SortDirection\u003A\u003AapplyToComparisonResult\u0028\u0029",
            "name": "applyToComparisonResult",
            "summary": "",
            "url": "classes/FastForward-Enum-Sort-SortDirection.html#method_applyToComparisonResult"
        },                {
            "fqsen": "\\FastForward\\Enum\\Sort\\SortDirection\u003A\u003AAscending",
            "name": "Ascending",
            "summary": "",
            "url": "classes/FastForward-Enum-Sort-SortDirection.html#enumcase_Ascending"
        },                {
            "fqsen": "\\FastForward\\Enum\\Sort\\SortDirection\u003A\u003ADescending",
            "name": "Descending",
            "summary": "",
            "url": "classes/FastForward-Enum-Sort-SortDirection.html#enumcase_Descending"
        },                {
            "fqsen": "\\FastForward\\Enum\\StateMachine\\HasTransitions",
            "name": "HasTransitions",
            "summary": "",
            "url": "classes/FastForward-Enum-StateMachine-HasTransitions.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\StateMachine\\HasTransitions\u003A\u003AtransitionMap\u0028\u0029",
            "name": "transitionMap",
            "summary": "",
            "url": "classes/FastForward-Enum-StateMachine-HasTransitions.html#method_transitionMap"
        },                {
            "fqsen": "\\FastForward\\Enum\\StateMachine\\HasTransitions\u003A\u003AinitialStateCases\u0028\u0029",
            "name": "initialStateCases",
            "summary": "",
            "url": "classes/FastForward-Enum-StateMachine-HasTransitions.html#method_initialStateCases"
        },                {
            "fqsen": "\\FastForward\\Enum\\StateMachine\\HasTransitions\u003A\u003AallowedTransitions\u0028\u0029",
            "name": "allowedTransitions",
            "summary": "",
            "url": "classes/FastForward-Enum-StateMachine-HasTransitions.html#method_allowedTransitions"
        },                {
            "fqsen": "\\FastForward\\Enum\\StateMachine\\HasTransitions\u003A\u003AcanTransitionTo\u0028\u0029",
            "name": "canTransitionTo",
            "summary": "",
            "url": "classes/FastForward-Enum-StateMachine-HasTransitions.html#method_canTransitionTo"
        },                {
            "fqsen": "\\FastForward\\Enum\\StateMachine\\HasTransitions\u003A\u003AassertCanTransitionTo\u0028\u0029",
            "name": "assertCanTransitionTo",
            "summary": "",
            "url": "classes/FastForward-Enum-StateMachine-HasTransitions.html#method_assertCanTransitionTo"
        },                {
            "fqsen": "\\FastForward\\Enum\\StateMachine\\HasTransitions\u003A\u003AisTerminal\u0028\u0029",
            "name": "isTerminal",
            "summary": "",
            "url": "classes/FastForward-Enum-StateMachine-HasTransitions.html#method_isTerminal"
        },                {
            "fqsen": "\\FastForward\\Enum\\StateMachine\\HasTransitions\u003A\u003AisInitial\u0028\u0029",
            "name": "isInitial",
            "summary": "",
            "url": "classes/FastForward-Enum-StateMachine-HasTransitions.html#method_isInitial"
        },                {
            "fqsen": "\\FastForward\\Enum\\StateMachine\\HasTransitions\u003A\u003AinitialStates\u0028\u0029",
            "name": "initialStates",
            "summary": "",
            "url": "classes/FastForward-Enum-StateMachine-HasTransitions.html#method_initialStates"
        },                {
            "fqsen": "\\FastForward\\Enum\\StateMachine\\HasTransitions\u003A\u003AterminalStates\u0028\u0029",
            "name": "terminalStates",
            "summary": "",
            "url": "classes/FastForward-Enum-StateMachine-HasTransitions.html#method_terminalStates"
        },                {
            "fqsen": "\\FastForward\\Enum\\StateMachine\\InvalidTransitionException",
            "name": "InvalidTransitionException",
            "summary": "",
            "url": "classes/FastForward-Enum-StateMachine-InvalidTransitionException.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\StateMachine\\InvalidTransitionException\u003A\u003Abetween\u0028\u0029",
            "name": "between",
            "summary": "",
            "url": "classes/FastForward-Enum-StateMachine-InvalidTransitionException.html#method_between"
        },                {
            "fqsen": "\\FastForward\\Enum\\Trait\\Comparable",
            "name": "Comparable",
            "summary": "",
            "url": "classes/FastForward-Enum-Trait-Comparable.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Trait\\Comparable\u003A\u003Ais\u0028\u0029",
            "name": "is",
            "summary": "",
            "url": "classes/FastForward-Enum-Trait-Comparable.html#method_is"
        },                {
            "fqsen": "\\FastForward\\Enum\\Trait\\Comparable\u003A\u003AisNot\u0028\u0029",
            "name": "isNot",
            "summary": "",
            "url": "classes/FastForward-Enum-Trait-Comparable.html#method_isNot"
        },                {
            "fqsen": "\\FastForward\\Enum\\Trait\\Comparable\u003A\u003Ain\u0028\u0029",
            "name": "in",
            "summary": "",
            "url": "classes/FastForward-Enum-Trait-Comparable.html#method_in"
        },                {
            "fqsen": "\\FastForward\\Enum\\Trait\\Comparable\u003A\u003AnotIn\u0028\u0029",
            "name": "notIn",
            "summary": "",
            "url": "classes/FastForward-Enum-Trait-Comparable.html#method_notIn"
        },                {
            "fqsen": "\\FastForward\\Enum\\Trait\\HasDescription",
            "name": "HasDescription",
            "summary": "",
            "url": "classes/FastForward-Enum-Trait-HasDescription.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Trait\\HasDescription\u003A\u003Adescription\u0028\u0029",
            "name": "description",
            "summary": "",
            "url": "classes/FastForward-Enum-Trait-HasDescription.html#method_description"
        },                {
            "fqsen": "\\FastForward\\Enum\\Trait\\HasLabel",
            "name": "HasLabel",
            "summary": "",
            "url": "classes/FastForward-Enum-Trait-HasLabel.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Trait\\HasLabel\u003A\u003Alabel\u0028\u0029",
            "name": "label",
            "summary": "",
            "url": "classes/FastForward-Enum-Trait-HasLabel.html#method_label"
        },                {
            "fqsen": "\\FastForward\\Enum\\Trait\\HasNameLookup",
            "name": "HasNameLookup",
            "summary": "",
            "url": "classes/FastForward-Enum-Trait-HasNameLookup.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Trait\\HasNameLookup\u003A\u003AtryFromName\u0028\u0029",
            "name": "tryFromName",
            "summary": "",
            "url": "classes/FastForward-Enum-Trait-HasNameLookup.html#method_tryFromName"
        },                {
            "fqsen": "\\FastForward\\Enum\\Trait\\HasNameLookup\u003A\u003AfromName\u0028\u0029",
            "name": "fromName",
            "summary": "",
            "url": "classes/FastForward-Enum-Trait-HasNameLookup.html#method_fromName"
        },                {
            "fqsen": "\\FastForward\\Enum\\Trait\\HasNameLookup\u003A\u003AhasName\u0028\u0029",
            "name": "hasName",
            "summary": "",
            "url": "classes/FastForward-Enum-Trait-HasNameLookup.html#method_hasName"
        },                {
            "fqsen": "\\FastForward\\Enum\\Trait\\HasNameMap",
            "name": "HasNameMap",
            "summary": "",
            "url": "classes/FastForward-Enum-Trait-HasNameMap.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Trait\\HasNameMap\u003A\u003AnameMap\u0028\u0029",
            "name": "nameMap",
            "summary": "",
            "url": "classes/FastForward-Enum-Trait-HasNameMap.html#method_nameMap"
        },                {
            "fqsen": "\\FastForward\\Enum\\Trait\\HasNames",
            "name": "HasNames",
            "summary": "",
            "url": "classes/FastForward-Enum-Trait-HasNames.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Trait\\HasNames\u003A\u003Anames\u0028\u0029",
            "name": "names",
            "summary": "",
            "url": "classes/FastForward-Enum-Trait-HasNames.html#method_names"
        },                {
            "fqsen": "\\FastForward\\Enum\\Trait\\HasOptions",
            "name": "HasOptions",
            "summary": "",
            "url": "classes/FastForward-Enum-Trait-HasOptions.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Trait\\HasOptions\u003A\u003Aoptions\u0028\u0029",
            "name": "options",
            "summary": "",
            "url": "classes/FastForward-Enum-Trait-HasOptions.html#method_options"
        },                {
            "fqsen": "\\FastForward\\Enum\\Trait\\HasValueMap",
            "name": "HasValueMap",
            "summary": "",
            "url": "classes/FastForward-Enum-Trait-HasValueMap.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Trait\\HasValueMap\u003A\u003AvalueMap\u0028\u0029",
            "name": "valueMap",
            "summary": "",
            "url": "classes/FastForward-Enum-Trait-HasValueMap.html#method_valueMap"
        },                {
            "fqsen": "\\FastForward\\Enum\\Trait\\HasValues",
            "name": "HasValues",
            "summary": "",
            "url": "classes/FastForward-Enum-Trait-HasValues.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Trait\\HasValues\u003A\u003Avalues\u0028\u0029",
            "name": "values",
            "summary": "",
            "url": "classes/FastForward-Enum-Trait-HasValues.html#method_values"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Calendar",
            "name": "Calendar",
            "summary": "",
            "url": "namespaces/fastforward-enum-calendar.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Common",
            "name": "Common",
            "summary": "",
            "url": "namespaces/fastforward-enum-common.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Comparison",
            "name": "Comparison",
            "summary": "",
            "url": "namespaces/fastforward-enum-comparison.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Container",
            "name": "Container",
            "summary": "",
            "url": "namespaces/fastforward-enum-container.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\DateTime",
            "name": "DateTime",
            "summary": "",
            "url": "namespaces/fastforward-enum-datetime.html"
        },                {
            "fqsen": "\\FastForward\\Enum",
            "name": "Enum",
            "summary": "",
            "url": "namespaces/fastforward-enum.html"
        },                {
            "fqsen": "\\FastForward",
            "name": "FastForward",
            "summary": "",
            "url": "namespaces/fastforward.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Event",
            "name": "Event",
            "summary": "",
            "url": "namespaces/fastforward-enum-event.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Helper",
            "name": "Helper",
            "summary": "",
            "url": "namespaces/fastforward-enum-helper.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Http",
            "name": "Http",
            "summary": "",
            "url": "namespaces/fastforward-enum-http.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Logger",
            "name": "Logger",
            "summary": "",
            "url": "namespaces/fastforward-enum-logger.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Outcome",
            "name": "Outcome",
            "summary": "",
            "url": "namespaces/fastforward-enum-outcome.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Pipeline",
            "name": "Pipeline",
            "summary": "",
            "url": "namespaces/fastforward-enum-pipeline.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Process",
            "name": "Process",
            "summary": "",
            "url": "namespaces/fastforward-enum-process.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Runtime",
            "name": "Runtime",
            "summary": "",
            "url": "namespaces/fastforward-enum-runtime.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Sort",
            "name": "Sort",
            "summary": "",
            "url": "namespaces/fastforward-enum-sort.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\StateMachine",
            "name": "StateMachine",
            "summary": "",
            "url": "namespaces/fastforward-enum-statemachine.html"
        },                {
            "fqsen": "\\FastForward\\Enum\\Trait",
            "name": "Trait",
            "summary": "",
            "url": "namespaces/fastforward-enum-trait.html"
        }            ]
);
