var classes = [
    {
        "name": "FastForward\\Enum\\StateMachine\\HasTransitions",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "transitionMap",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "initialStateCases",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "allowedTransitions",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "canTransitionTo",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "assertCanTransitionTo",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isTerminal",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isInitial",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "initialStates",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "terminalStates",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 9,
        "nbMethods": 9,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 14,
        "ccn": 6,
        "ccnMethodMax": 4,
        "externals": [
            "FastForward\\Enum\\StateMachine\\InvalidTransitionException",
            "static"
        ],
        "parents": [],
        "implements": [],
        "lcom": 6,
        "length": 41,
        "vocabulary": 12,
        "volume": 146.98,
        "difficulty": 12.5,
        "effort": 1837.29,
        "level": 0.08,
        "bugs": 0.05,
        "time": 102,
        "intelligentContent": 11.76,
        "number_operators": 16,
        "number_operands": 25,
        "number_operators_unique": 6,
        "number_operands_unique": 6,
        "cloc": 31,
        "loc": 80,
        "lloc": 49,
        "mi": 88.23,
        "mIwoC": 47.15,
        "commentWeight": 41.08,
        "kanDefect": 0.75,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.91,
        "relativeSystemComplexity": 64.91,
        "totalStructuralComplexity": 576,
        "totalDataComplexity": 8.22,
        "totalSystemComplexity": 584.22,
        "package": "FastForward\\Enum\\StateMachine\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\StateMachine\\InvalidTransitionException",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "between",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "DomainException",
            "UnitEnum",
            "UnitEnum"
        ],
        "parents": [
            "DomainException"
        ],
        "implements": [],
        "lcom": 1,
        "length": 8,
        "vocabulary": 4,
        "volume": 16,
        "difficulty": 1.17,
        "effort": 18.67,
        "level": 0.86,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 13.71,
        "number_operators": 1,
        "number_operands": 7,
        "number_operators_unique": 1,
        "number_operands_unique": 3,
        "cloc": 6,
        "loc": 14,
        "lloc": 8,
        "mi": 114.19,
        "mIwoC": 71.73,
        "commentWeight": 42.45,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 3,
        "package": "FastForward\\Enum\\StateMachine\\",
        "pageRank": 0.07,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Helper\\EnumHelper",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "cases",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "names",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "values",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "nameMap",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "valueMap",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "options",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "hasName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "hasValue",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "tryFromName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "labels",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "labelMap",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "unitEnumClass",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "backedEnumClass",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "labeledEnumClass",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 15,
        "nbMethods": 15,
        "nbMethodsPrivate": 3,
        "nbMethodsPublic": 12,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 28,
        "ccn": 14,
        "ccnMethodMax": 4,
        "externals": [
            "enumClass",
            "enumClass",
            "enumClass",
            "enumClass",
            "enumClass",
            "enumClass",
            "enumClass",
            "UnitEnum",
            "ValueError",
            "enumClass",
            "enumClass",
            "ValueError",
            "ValueError",
            "ValueError"
        ],
        "parents": [],
        "implements": [],
        "lcom": 15,
        "length": 156,
        "vocabulary": 17,
        "volume": 637.64,
        "difficulty": 30.55,
        "effort": 19477.13,
        "level": 0.03,
        "bugs": 0.21,
        "time": 1082,
        "intelligentContent": 20.88,
        "number_operators": 44,
        "number_operands": 112,
        "number_operators_unique": 6,
        "number_operands_unique": 11,
        "cloc": 108,
        "loc": 210,
        "lloc": 102,
        "mi": 79.47,
        "mIwoC": 34.66,
        "commentWeight": 44.81,
        "kanDefect": 1.28,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 1.81,
        "relativeSystemComplexity": 65.81,
        "totalStructuralComplexity": 960,
        "totalDataComplexity": 27.11,
        "totalSystemComplexity": 987.11,
        "package": "FastForward\\Enum\\Helper\\",
        "pageRank": 0.52,
        "afferentCoupling": 6,
        "efferentCoupling": 3,
        "instability": 0.33,
        "numberOfUnitTests": 22,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Trait\\HasValues",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "values",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "FastForward\\Enum\\Helper\\EnumHelper"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 3,
        "loc": 11,
        "lloc": 8,
        "mi": 207.18,
        "mIwoC": 171,
        "commentWeight": 36.18,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "FastForward\\Enum\\Trait\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Trait\\HasNameLookup",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "tryFromName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "hasName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "FastForward\\Enum\\Helper\\EnumHelper",
            "FastForward\\Enum\\Helper\\EnumHelper",
            "FastForward\\Enum\\Helper\\EnumHelper"
        ],
        "parents": [],
        "implements": [],
        "lcom": 3,
        "length": 15,
        "vocabulary": 4,
        "volume": 30,
        "difficulty": 5,
        "effort": 150,
        "level": 0.2,
        "bugs": 0.01,
        "time": 8,
        "intelligentContent": 6,
        "number_operators": 5,
        "number_operands": 10,
        "number_operators_unique": 2,
        "number_operands_unique": 2,
        "cloc": 17,
        "loc": 35,
        "lloc": 18,
        "mi": 106.23,
        "mIwoC": 62.14,
        "commentWeight": 44.09,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 10,
        "totalStructuralComplexity": 27,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 30,
        "package": "FastForward\\Enum\\Trait\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Trait\\Comparable",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "is",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isNot",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "in",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "notIn",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 3,
        "length": 18,
        "vocabulary": 6,
        "volume": 46.53,
        "difficulty": 6,
        "effort": 279.18,
        "level": 0.17,
        "bugs": 0.02,
        "time": 16,
        "intelligentContent": 7.75,
        "number_operators": 6,
        "number_operands": 12,
        "number_operators_unique": 3,
        "number_operands_unique": 3,
        "cloc": 16,
        "loc": 36,
        "lloc": 20,
        "mi": 102.74,
        "mIwoC": 59.81,
        "commentWeight": 42.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 2.5,
        "relativeSystemComplexity": 3.5,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 10,
        "totalSystemComplexity": 14,
        "package": "FastForward\\Enum\\Trait\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Trait\\HasLabel",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "label",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 3,
        "vocabulary": 3,
        "volume": 4.75,
        "difficulty": 0.5,
        "effort": 2.38,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 9.51,
        "number_operators": 1,
        "number_operands": 2,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 3,
        "loc": 11,
        "lloc": 8,
        "mi": 111.61,
        "mIwoC": 75.43,
        "commentWeight": 36.18,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "FastForward\\Enum\\Trait\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Trait\\HasOptions",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "options",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "FastForward\\Enum\\Helper\\EnumHelper"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 3,
        "loc": 11,
        "lloc": 8,
        "mi": 207.18,
        "mIwoC": 171,
        "commentWeight": 36.18,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "FastForward\\Enum\\Trait\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Trait\\HasNameMap",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "nameMap",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "FastForward\\Enum\\Helper\\EnumHelper"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 4,
        "vocabulary": 3,
        "volume": 6.34,
        "difficulty": 2,
        "effort": 12.68,
        "level": 0.5,
        "bugs": 0,
        "time": 1,
        "intelligentContent": 3.17,
        "number_operators": 2,
        "number_operands": 2,
        "number_operators_unique": 2,
        "number_operands_unique": 1,
        "cloc": 4,
        "loc": 13,
        "lloc": 9,
        "mi": 111.3,
        "mIwoC": 73.43,
        "commentWeight": 37.87,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "FastForward\\Enum\\Trait\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Trait\\HasValueMap",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "valueMap",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "FastForward\\Enum\\Helper\\EnumHelper"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 4,
        "vocabulary": 3,
        "volume": 6.34,
        "difficulty": 2,
        "effort": 12.68,
        "level": 0.5,
        "bugs": 0,
        "time": 1,
        "intelligentContent": 3.17,
        "number_operators": 2,
        "number_operands": 2,
        "number_operators_unique": 2,
        "number_operands_unique": 1,
        "cloc": 4,
        "loc": 13,
        "lloc": 9,
        "mi": 111.3,
        "mIwoC": 73.43,
        "commentWeight": 37.87,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "FastForward\\Enum\\Trait\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Trait\\HasDescription",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "description",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 9,
        "vocabulary": 7,
        "volume": 25.27,
        "difficulty": 2.25,
        "effort": 56.85,
        "level": 0.44,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 11.23,
        "number_operators": 3,
        "number_operands": 6,
        "number_operators_unique": 3,
        "number_operands_unique": 4,
        "cloc": 3,
        "loc": 12,
        "lloc": 9,
        "mi": 104.07,
        "mIwoC": 69.09,
        "commentWeight": 34.97,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "FastForward\\Enum\\Trait\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Trait\\HasNames",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "names",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "FastForward\\Enum\\Helper\\EnumHelper"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 3,
        "loc": 11,
        "lloc": 8,
        "mi": 207.18,
        "mIwoC": 171,
        "commentWeight": 36.18,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "FastForward\\Enum\\Trait\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "numberOfUnitTests": 0,
        "violations": {}
    }
]