name: "Fast Forward Test Suite"

on:
  push:
  workflow_dispatch:
    inputs:
      max-outdated:
        description: Maximum number of outdated packages allowed by the dependencies command.
        required: false
        type: number
        default: -1

permissions:
  contents: read

jobs:
  tests:
    uses: php-fast-forward/dev-tools/.github/workflows/tests.yml@main
    with:
      max-outdated: ${{ inputs.max-outdated || -1 }}
    secrets: inherit
