var classes = [
    {
        "name": "FastForward\\Enum\\StateMachine\\HasTransitions",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "transitionMap",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "initialStateCases",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "allowedTransitions",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "canTransitionTo",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "assertCanTransitionTo",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isTerminal",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isInitial",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "initialStates",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "terminalStates",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 9,
        "nbMethods": 9,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 14,
        "ccn": 6,
        "ccnMethodMax": 4,
        "externals": [
            "FastForward\\Enum\\StateMachine\\InvalidTransitionException",
            "static"
        ],
        "parents": [],
        "implements": [],
        "lcom": 6,
        "length": 41,
        "vocabulary": 12,
        "volume": 146.98,
        "difficulty": 12.5,
        "effort": 1837.29,
        "level": 0.08,
        "bugs": 0.05,
        "time": 102,
        "intelligentContent": 11.76,
        "number_operators": 16,
        "number_operands": 25,
        "number_operators_unique": 6,
        "number_operands_unique": 6,
        "cloc": 31,
        "loc": 80,
        "lloc": 49,
        "mi": 88.23,
        "mIwoC": 47.15,
        "commentWeight": 41.08,
        "kanDefect": 0.75,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.91,
        "relativeSystemComplexity": 64.91,
        "totalStructuralComplexity": 576,
        "totalDataComplexity": 8.22,
        "totalSystemComplexity": 584.22,
        "package": "FastForward\\Enum\\StateMachine\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\StateMachine\\InvalidTransitionException",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "between",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "DomainException",
            "UnitEnum",
            "UnitEnum"
        ],
        "parents": [
            "DomainException"
        ],
        "implements": [],
        "lcom": 1,
        "length": 8,
        "vocabulary": 4,
        "volume": 16,
        "difficulty": 1.17,
        "effort": 18.67,
        "level": 0.86,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 13.71,
        "number_operators": 1,
        "number_operands": 7,
        "number_operators_unique": 1,
        "number_operands_unique": 3,
        "cloc": 6,
        "loc": 14,
        "lloc": 8,
        "mi": 114.19,
        "mIwoC": 71.73,
        "commentWeight": 42.45,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 3,
        "package": "FastForward\\Enum\\StateMachine\\",
        "pageRank": 0.04,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Helper\\EnumHelper",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "cases",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "names",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "values",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "nameMap",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "valueMap",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "options",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "hasName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "hasValue",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "tryFromName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "labels",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "labelMap",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "unitEnumClass",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "backedEnumClass",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "labeledEnumClass",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 15,
        "nbMethods": 15,
        "nbMethodsPrivate": 3,
        "nbMethodsPublic": 12,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 28,
        "ccn": 14,
        "ccnMethodMax": 4,
        "externals": [
            "enumClass",
            "enumClass",
            "enumClass",
            "enumClass",
            "enumClass",
            "enumClass",
            "enumClass",
            "UnitEnum",
            "ValueError",
            "enumClass",
            "enumClass",
            "ValueError",
            "ValueError",
            "ValueError"
        ],
        "parents": [],
        "implements": [],
        "lcom": 15,
        "length": 156,
        "vocabulary": 17,
        "volume": 637.64,
        "difficulty": 30.55,
        "effort": 19477.13,
        "level": 0.03,
        "bugs": 0.21,
        "time": 1082,
        "intelligentContent": 20.88,
        "number_operators": 44,
        "number_operands": 112,
        "number_operators_unique": 6,
        "number_operands_unique": 11,
        "cloc": 108,
        "loc": 210,
        "lloc": 102,
        "mi": 79.47,
        "mIwoC": 34.66,
        "commentWeight": 44.81,
        "kanDefect": 1.28,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 1.81,
        "relativeSystemComplexity": 65.81,
        "totalStructuralComplexity": 960,
        "totalDataComplexity": 27.11,
        "totalSystemComplexity": 987.11,
        "package": "FastForward\\Enum\\Helper\\",
        "pageRank": 0.4,
        "afferentCoupling": 7,
        "efferentCoupling": 3,
        "instability": 0.3,
        "numberOfUnitTests": 26,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Trait\\HasValues",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "values",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "FastForward\\Enum\\Helper\\EnumHelper"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 3,
        "loc": 11,
        "lloc": 8,
        "mi": 207.18,
        "mIwoC": 171,
        "commentWeight": 36.18,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "FastForward\\Enum\\Trait\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Trait\\HasNameLookup",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "tryFromName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "hasName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "FastForward\\Enum\\Helper\\EnumHelper",
            "FastForward\\Enum\\Helper\\EnumHelper",
            "FastForward\\Enum\\Helper\\EnumHelper"
        ],
        "parents": [],
        "implements": [],
        "lcom": 3,
        "length": 15,
        "vocabulary": 4,
        "volume": 30,
        "difficulty": 5,
        "effort": 150,
        "level": 0.2,
        "bugs": 0.01,
        "time": 8,
        "intelligentContent": 6,
        "number_operators": 5,
        "number_operands": 10,
        "number_operators_unique": 2,
        "number_operands_unique": 2,
        "cloc": 17,
        "loc": 35,
        "lloc": 18,
        "mi": 106.23,
        "mIwoC": 62.14,
        "commentWeight": 44.09,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 10,
        "totalStructuralComplexity": 27,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 30,
        "package": "FastForward\\Enum\\Trait\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Trait\\Comparable",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "is",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isNot",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "in",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "notIn",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 3,
        "length": 18,
        "vocabulary": 6,
        "volume": 46.53,
        "difficulty": 6,
        "effort": 279.18,
        "level": 0.17,
        "bugs": 0.02,
        "time": 16,
        "intelligentContent": 7.75,
        "number_operators": 6,
        "number_operands": 12,
        "number_operators_unique": 3,
        "number_operands_unique": 3,
        "cloc": 16,
        "loc": 36,
        "lloc": 20,
        "mi": 102.74,
        "mIwoC": 59.81,
        "commentWeight": 42.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 2.5,
        "relativeSystemComplexity": 3.5,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 10,
        "totalSystemComplexity": 14,
        "package": "FastForward\\Enum\\Trait\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Trait\\HasLabel",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "label",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 3,
        "vocabulary": 3,
        "volume": 4.75,
        "difficulty": 0.5,
        "effort": 2.38,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 9.51,
        "number_operators": 1,
        "number_operands": 2,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 3,
        "loc": 11,
        "lloc": 8,
        "mi": 111.61,
        "mIwoC": 75.43,
        "commentWeight": 36.18,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "FastForward\\Enum\\Trait\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Trait\\HasOptions",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "options",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "FastForward\\Enum\\Helper\\EnumHelper"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 3,
        "loc": 11,
        "lloc": 8,
        "mi": 207.18,
        "mIwoC": 171,
        "commentWeight": 36.18,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "FastForward\\Enum\\Trait\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Trait\\HasNameMap",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "nameMap",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "FastForward\\Enum\\Helper\\EnumHelper"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 4,
        "vocabulary": 3,
        "volume": 6.34,
        "difficulty": 2,
        "effort": 12.68,
        "level": 0.5,
        "bugs": 0,
        "time": 1,
        "intelligentContent": 3.17,
        "number_operators": 2,
        "number_operands": 2,
        "number_operators_unique": 2,
        "number_operands_unique": 1,
        "cloc": 4,
        "loc": 13,
        "lloc": 9,
        "mi": 111.3,
        "mIwoC": 73.43,
        "commentWeight": 37.87,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "FastForward\\Enum\\Trait\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Trait\\HasValueMap",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "valueMap",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "FastForward\\Enum\\Helper\\EnumHelper"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 4,
        "vocabulary": 3,
        "volume": 6.34,
        "difficulty": 2,
        "effort": 12.68,
        "level": 0.5,
        "bugs": 0,
        "time": 1,
        "intelligentContent": 3.17,
        "number_operators": 2,
        "number_operands": 2,
        "number_operators_unique": 2,
        "number_operands_unique": 1,
        "cloc": 4,
        "loc": 13,
        "lloc": 9,
        "mi": 111.3,
        "mIwoC": 73.43,
        "commentWeight": 37.87,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "FastForward\\Enum\\Trait\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Trait\\HasDescription",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "description",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 9,
        "vocabulary": 7,
        "volume": 25.27,
        "difficulty": 2.25,
        "effort": 56.85,
        "level": 0.44,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 11.23,
        "number_operators": 3,
        "number_operands": 6,
        "number_operators_unique": 3,
        "number_operands_unique": 4,
        "cloc": 3,
        "loc": 12,
        "lloc": 9,
        "mi": 104.07,
        "mIwoC": 69.09,
        "commentWeight": 34.97,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "FastForward\\Enum\\Trait\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Trait\\HasNames",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "names",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "FastForward\\Enum\\Helper\\EnumHelper"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 3,
        "loc": 11,
        "lloc": 8,
        "mi": 207.18,
        "mIwoC": 171,
        "commentWeight": 36.18,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "FastForward\\Enum\\Trait\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Tests\\Http\\SchemeTest",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "itExposesStableBackedValues",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itProvidesDefaultPorts",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itIdentifiesSecureSchemes",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itDescribesSchemes",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "PHPUnit\\Framework\\TestCase",
            "FastForward\\Enum\\Http\\Scheme"
        ],
        "parents": [
            "PHPUnit\\Framework\\TestCase"
        ],
        "implements": [],
        "lcom": 4,
        "length": 6,
        "vocabulary": 6,
        "volume": 15.51,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 31.02,
        "number_operators": 0,
        "number_operands": 6,
        "number_operators_unique": 0,
        "number_operands_unique": 6,
        "cloc": 18,
        "loc": 41,
        "lloc": 23,
        "mi": 104.6,
        "mIwoC": 61.82,
        "commentWeight": 42.77,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 49,
        "totalStructuralComplexity": 196,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 196,
        "package": "FastForward\\Enum\\Tests\\Http\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Tests\\StateMachine\\HasTransitionsTest",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "itSupportsStateMachineStyleTransitions",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itInfersInitialStatesWhenNoInitialStateCasesAreConfigured",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itThrowsForInvalidStateMachineTransitions",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "PHPUnit\\Framework\\TestCase",
            "FastForward\\Enum\\Tests\\Support\\ArticleWorkflow",
            "FastForward\\Enum\\Tests\\Support\\ArticleWorkflow",
            "FastForward\\Enum\\Tests\\Support\\InferredWorkflow",
            "FastForward\\Enum\\Tests\\Support\\InferredWorkflow"
        ],
        "parents": [
            "PHPUnit\\Framework\\TestCase"
        ],
        "implements": [],
        "lcom": 3,
        "length": 3,
        "vocabulary": 2,
        "volume": 3,
        "difficulty": 0,
        "effort": 0,
        "level": 1.33,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 0,
        "number_operands": 3,
        "number_operators_unique": 0,
        "number_operands_unique": 2,
        "cloc": 14,
        "loc": 44,
        "lloc": 30,
        "mi": 102.64,
        "mIwoC": 64.3,
        "commentWeight": 38.34,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 225,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 225,
        "totalStructuralComplexity": 675,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 675,
        "package": "FastForward\\Enum\\Tests\\StateMachine\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Tests\\Logger\\LogLevelTest",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "itComparesLogLevelWeights",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itKeepsLogLevelOrder",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itDescribesLogLevels",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "PHPUnit\\Framework\\TestCase",
            "FastForward\\Enum\\Logger\\LogLevel",
            "FastForward\\Enum\\Logger\\LogLevel"
        ],
        "parents": [
            "PHPUnit\\Framework\\TestCase"
        ],
        "implements": [],
        "lcom": 3,
        "length": 11,
        "vocabulary": 10,
        "volume": 36.54,
        "difficulty": 0,
        "effort": 0,
        "level": 1.82,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 66.44,
        "number_operators": 0,
        "number_operands": 11,
        "number_operators_unique": 0,
        "number_operands_unique": 10,
        "cloc": 13,
        "loc": 31,
        "lloc": 18,
        "mi": 103.7,
        "mIwoC": 61.54,
        "commentWeight": 42.16,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 64,
        "totalStructuralComplexity": 192,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 192,
        "package": "FastForward\\Enum\\Tests\\Logger\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Tests\\Sort\\SortDirectionTest",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "itProvidesEnumHelpersForSortDirection",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itProvidesSortSpecificHelpers",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itProvidesNullsPositionHelpers",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itProvidesCaseSensitivityHelpers",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "PHPUnit\\Framework\\TestCase",
            "FastForward\\Enum\\Sort\\SortDirection",
            "FastForward\\Enum\\Sort\\SortDirection",
            "FastForward\\Enum\\Sort\\SortDirection",
            "FastForward\\Enum\\Sort\\NullsPosition",
            "FastForward\\Enum\\Sort\\CaseSensitivity"
        ],
        "parents": [
            "PHPUnit\\Framework\\TestCase"
        ],
        "implements": [],
        "lcom": 4,
        "length": 34,
        "vocabulary": 17,
        "volume": 138.97,
        "difficulty": 0,
        "effort": 0,
        "level": 1,
        "bugs": 0.05,
        "time": 0,
        "intelligentContent": 138.97,
        "number_operators": 0,
        "number_operands": 34,
        "number_operators_unique": 0,
        "number_operands_unique": 17,
        "cloc": 20,
        "loc": 67,
        "lloc": 47,
        "mi": 85.83,
        "mIwoC": 48.39,
        "commentWeight": 37.45,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 529,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 529,
        "totalStructuralComplexity": 2116,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 2116,
        "package": "FastForward\\Enum\\Tests\\Sort\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Tests\\Sort\\ComparisonResultTest",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "itProvidesNamesAndNameLookupHelpers",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itConvertsComparatorResultsToComparisonResultCases",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itConvertsComparisonResultCasesBackToComparatorResults",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itCanBeReversedAndCheckedForComparability",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "PHPUnit\\Framework\\TestCase",
            "FastForward\\Enum\\Sort\\ComparisonResult",
            "FastForward\\Enum\\Sort\\ComparisonResult",
            "FastForward\\Enum\\Sort\\ComparisonResult",
            "FastForward\\Enum\\Sort\\ComparisonResult",
            "FastForward\\Enum\\Sort\\ComparisonResult",
            "FastForward\\Enum\\Sort\\ComparisonResult",
            "FastForward\\Enum\\Sort\\ComparisonResult",
            "FastForward\\Enum\\Sort\\ComparisonResult",
            "FastForward\\Enum\\Sort\\ComparisonResult"
        ],
        "parents": [
            "PHPUnit\\Framework\\TestCase"
        ],
        "implements": [],
        "lcom": 4,
        "length": 16,
        "vocabulary": 8,
        "volume": 48,
        "difficulty": 0,
        "effort": 0,
        "level": 1,
        "bugs": 0.02,
        "time": 0,
        "intelligentContent": 48,
        "number_operators": 0,
        "number_operands": 16,
        "number_operators_unique": 0,
        "number_operands_unique": 8,
        "cloc": 18,
        "loc": 54,
        "lloc": 36,
        "mi": 93.14,
        "mIwoC": 54.14,
        "commentWeight": 38.99,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 144,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 144,
        "totalStructuralComplexity": 576,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 576,
        "package": "FastForward\\Enum\\Tests\\Sort\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Tests\\Runtime\\EnvironmentTest",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "itExposesStableBackedValues",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itIdentifiesProductionAndPreProductionEnvironments",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itIdentifiesDebugFriendlyEnvironments",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itDescribesEnvironments",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "PHPUnit\\Framework\\TestCase",
            "FastForward\\Enum\\Runtime\\Environment"
        ],
        "parents": [
            "PHPUnit\\Framework\\TestCase"
        ],
        "implements": [],
        "lcom": 4,
        "length": 5,
        "vocabulary": 5,
        "volume": 11.61,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 23.22,
        "number_operators": 0,
        "number_operands": 5,
        "number_operators_unique": 0,
        "number_operands_unique": 5,
        "cloc": 18,
        "loc": 40,
        "lloc": 22,
        "mi": 106.23,
        "mIwoC": 63.13,
        "commentWeight": 43.1,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 64,
        "totalStructuralComplexity": 256,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 256,
        "package": "FastForward\\Enum\\Tests\\Runtime\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Tests\\Outcome\\ResultTest",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "itIdentifiesSuccessfulResults",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itDescribesResults",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "PHPUnit\\Framework\\TestCase"
        ],
        "parents": [
            "PHPUnit\\Framework\\TestCase"
        ],
        "implements": [],
        "lcom": 2,
        "length": 1,
        "vocabulary": 1,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 1,
        "number_operators_unique": 0,
        "number_operands_unique": 1,
        "cloc": 9,
        "loc": 24,
        "lloc": 15,
        "mi": 211.63,
        "mIwoC": 171,
        "commentWeight": 40.63,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 36,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 72,
        "package": "FastForward\\Enum\\Tests\\Outcome\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Tests\\Event\\DispatchModeTest",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "itExposesStableBackedValues",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itIdentifiesSyncAndAsyncDispatch",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itDescribesDispatchModes",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "PHPUnit\\Framework\\TestCase",
            "FastForward\\Enum\\Event\\DispatchMode"
        ],
        "parents": [
            "PHPUnit\\Framework\\TestCase"
        ],
        "implements": [],
        "lcom": 3,
        "length": 4,
        "vocabulary": 4,
        "volume": 8,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 16,
        "number_operators": 0,
        "number_operands": 4,
        "number_operators_unique": 0,
        "number_operands_unique": 4,
        "cloc": 14,
        "loc": 34,
        "lloc": 20,
        "mi": 107.07,
        "mIwoC": 65.16,
        "commentWeight": 41.91,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 49,
        "totalStructuralComplexity": 147,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 147,
        "package": "FastForward\\Enum\\Tests\\Event\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Tests\\Common\\PriorityTest",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "itOrdersPrioritiesByWeight",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itComparesPriorityWeights",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itDescribesPriorities",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "PHPUnit\\Framework\\TestCase",
            "FastForward\\Enum\\Common\\Priority"
        ],
        "parents": [
            "PHPUnit\\Framework\\TestCase"
        ],
        "implements": [],
        "lcom": 3,
        "length": 2,
        "vocabulary": 2,
        "volume": 2,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 0,
        "number_operands": 2,
        "number_operators_unique": 0,
        "number_operands_unique": 2,
        "cloc": 13,
        "loc": 31,
        "lloc": 18,
        "mi": 112.54,
        "mIwoC": 70.38,
        "commentWeight": 42.16,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 49,
        "totalStructuralComplexity": 147,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 147,
        "package": "FastForward\\Enum\\Tests\\Common\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Tests\\Common\\SeverityTest",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "itComparesSeverityWeights",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itKeepsSeverityOrder",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itDescribesSeverities",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "PHPUnit\\Framework\\TestCase",
            "FastForward\\Enum\\Common\\Severity"
        ],
        "parents": [
            "PHPUnit\\Framework\\TestCase"
        ],
        "implements": [],
        "lcom": 3,
        "length": 2,
        "vocabulary": 2,
        "volume": 2,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 0,
        "number_operands": 2,
        "number_operators_unique": 0,
        "number_operands_unique": 2,
        "cloc": 13,
        "loc": 31,
        "lloc": 18,
        "mi": 112.54,
        "mIwoC": 70.38,
        "commentWeight": 42.16,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 49,
        "totalStructuralComplexity": 147,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 147,
        "package": "FastForward\\Enum\\Tests\\Common\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Tests\\DateTime\\IntervalUnitTest",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "itExposesShortLabels",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itConvertsUnitsToSeconds",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itIdentifiesCalendarAwareUnits",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itDescribesIntervalUnits",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "PHPUnit\\Framework\\TestCase",
            "FastForward\\Enum\\DateTime\\IntervalUnit",
            "FastForward\\Enum\\DateTime\\IntervalUnit"
        ],
        "parents": [
            "PHPUnit\\Framework\\TestCase"
        ],
        "implements": [],
        "lcom": 4,
        "length": 27,
        "vocabulary": 24,
        "volume": 123.79,
        "difficulty": 0,
        "effort": 0,
        "level": 1.78,
        "bugs": 0.04,
        "time": 0,
        "intelligentContent": 220.08,
        "number_operators": 0,
        "number_operands": 27,
        "number_operators_unique": 0,
        "number_operands_unique": 24,
        "cloc": 17,
        "loc": 44,
        "lloc": 27,
        "mi": 95.03,
        "mIwoC": 53.99,
        "commentWeight": 41.04,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 64,
        "totalStructuralComplexity": 256,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 256,
        "package": "FastForward\\Enum\\Tests\\DateTime\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Tests\\Pipeline\\FailureModeTest",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "itExposesStableBackedValues",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itIdentifiesStopOnFailureModes",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itDescribesFailureModes",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "PHPUnit\\Framework\\TestCase",
            "FastForward\\Enum\\Pipeline\\FailureMode"
        ],
        "parents": [
            "PHPUnit\\Framework\\TestCase"
        ],
        "implements": [],
        "lcom": 3,
        "length": 4,
        "vocabulary": 4,
        "volume": 8,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 16,
        "number_operators": 0,
        "number_operands": 4,
        "number_operators_unique": 0,
        "number_operands_unique": 4,
        "cloc": 14,
        "loc": 32,
        "lloc": 18,
        "mi": 108.89,
        "mIwoC": 66.16,
        "commentWeight": 42.73,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 36,
        "totalStructuralComplexity": 108,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 108,
        "package": "FastForward\\Enum\\Tests\\Pipeline\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Tests\\Process\\SignalBehaviorTest",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "itExposesStableBackedValues",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itIdentifiesTerminalControlBehaviors",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itDescribesSignalBehaviors",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "PHPUnit\\Framework\\TestCase",
            "FastForward\\Enum\\Process\\SignalBehavior"
        ],
        "parents": [
            "PHPUnit\\Framework\\TestCase"
        ],
        "implements": [],
        "lcom": 3,
        "length": 6,
        "vocabulary": 6,
        "volume": 15.51,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 31.02,
        "number_operators": 0,
        "number_operands": 6,
        "number_operators_unique": 0,
        "number_operands_unique": 6,
        "cloc": 14,
        "loc": 34,
        "lloc": 20,
        "mi": 105.06,
        "mIwoC": 63.15,
        "commentWeight": 41.91,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 36,
        "totalStructuralComplexity": 108,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 108,
        "package": "FastForward\\Enum\\Tests\\Process\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Tests\\Container\\ServiceLifetimeTest",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "itExposesStableBackedValues",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itIdentifiesReusableLifetimes",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itDescribesServiceLifetimes",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "PHPUnit\\Framework\\TestCase",
            "FastForward\\Enum\\Container\\ServiceLifetime"
        ],
        "parents": [
            "PHPUnit\\Framework\\TestCase"
        ],
        "implements": [],
        "lcom": 3,
        "length": 4,
        "vocabulary": 4,
        "volume": 8,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 16,
        "number_operators": 0,
        "number_operands": 4,
        "number_operators_unique": 0,
        "number_operands_unique": 4,
        "cloc": 14,
        "loc": 32,
        "lloc": 18,
        "mi": 108.89,
        "mIwoC": 66.16,
        "commentWeight": 42.73,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 36,
        "totalStructuralComplexity": 108,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 108,
        "package": "FastForward\\Enum\\Tests\\Container\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Tests\\Helper\\EnumHelperTest",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "itReturnsCasesForUnitEnums",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itReturnsNamesForUnitEnums",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itReturnsValuesForBackedEnums",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itBuildsMapsForNamesAndValues",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itBuildsOptionsForBackedEnums",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itCanLookUpCasesByName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itThrowsForInvalidNames",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itChecksForBackedValues",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itRejectsNonBackedEnumClassStringsForBackedHelpers",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itRejectsNonEnumClassStringsForUnitHelpers",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itExposesLabelsForLabeledEnums",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itRejectsNonLabeledEnumsForLabelHelpers",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 12,
        "nbMethods": 12,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 12,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 12,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "PHPUnit\\Framework\\TestCase",
            "FastForward\\Enum\\Helper\\EnumHelper",
            "FastForward\\Enum\\Helper\\EnumHelper",
            "FastForward\\Enum\\Helper\\EnumHelper",
            "FastForward\\Enum\\Helper\\EnumHelper",
            "FastForward\\Enum\\Helper\\EnumHelper",
            "FastForward\\Enum\\Helper\\EnumHelper",
            "FastForward\\Enum\\Helper\\EnumHelper",
            "FastForward\\Enum\\Helper\\EnumHelper",
            "FastForward\\Enum\\Helper\\EnumHelper",
            "FastForward\\Enum\\Helper\\EnumHelper",
            "FastForward\\Enum\\Helper\\EnumHelper",
            "FastForward\\Enum\\Helper\\EnumHelper",
            "FastForward\\Enum\\Helper\\EnumHelper",
            "FastForward\\Enum\\Helper\\EnumHelper",
            "FastForward\\Enum\\Helper\\EnumHelper",
            "FastForward\\Enum\\Helper\\EnumHelper",
            "FastForward\\Enum\\Helper\\EnumHelper",
            "FastForward\\Enum\\Helper\\EnumHelper",
            "FastForward\\Enum\\Helper\\EnumHelper",
            "FastForward\\Enum\\Helper\\EnumHelper",
            "FastForward\\Enum\\Helper\\EnumHelper",
            "FastForward\\Enum\\Helper\\EnumHelper",
            "FastForward\\Enum\\Helper\\EnumHelper",
            "FastForward\\Enum\\Helper\\EnumHelper",
            "FastForward\\Enum\\Helper\\EnumHelper",
            "FastForward\\Enum\\Helper\\EnumHelper"
        ],
        "parents": [
            "PHPUnit\\Framework\\TestCase"
        ],
        "implements": [],
        "lcom": 9,
        "length": 68,
        "vocabulary": 23,
        "volume": 307.6,
        "difficulty": 1.27,
        "effort": 391.49,
        "level": 0.79,
        "bugs": 0.1,
        "time": 22,
        "intelligentContent": 241.69,
        "number_operators": 12,
        "number_operands": 56,
        "number_operators_unique": 1,
        "number_operands_unique": 22,
        "cloc": 50,
        "loc": 124,
        "lloc": 74,
        "mi": 83.3,
        "mIwoC": 41.67,
        "commentWeight": 41.63,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 324,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 324,
        "totalStructuralComplexity": 3888,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 3888,
        "package": "FastForward\\Enum\\Tests\\Helper\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Tests\\Calendar\\WeekdayTest",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "itIdentifiesWeekendsAndWeekdays",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itKeepsIsoWeekOrder",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itDescribesWeekdays",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "PHPUnit\\Framework\\TestCase",
            "FastForward\\Enum\\Calendar\\Weekday",
            "FastForward\\Enum\\Calendar\\Weekday"
        ],
        "parents": [
            "PHPUnit\\Framework\\TestCase"
        ],
        "implements": [],
        "lcom": 3,
        "length": 9,
        "vocabulary": 8,
        "volume": 27,
        "difficulty": 0,
        "effort": 0,
        "level": 1.78,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 48,
        "number_operators": 0,
        "number_operands": 9,
        "number_operators_unique": 0,
        "number_operands_unique": 8,
        "cloc": 13,
        "loc": 31,
        "lloc": 18,
        "mi": 104.62,
        "mIwoC": 62.46,
        "commentWeight": 42.16,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 64,
        "totalStructuralComplexity": 192,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 192,
        "package": "FastForward\\Enum\\Tests\\Calendar\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Tests\\Calendar\\MonthTest",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "itKeepsCalendarDeclarationOrder",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itIdentifiesTheQuarterForAMonth",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itIdentifiesQuarterEndMonths",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itDescribesMonths",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "PHPUnit\\Framework\\TestCase",
            "FastForward\\Enum\\Calendar\\Month",
            "FastForward\\Enum\\Calendar\\Month",
            "FastForward\\Enum\\Calendar\\Month"
        ],
        "parents": [
            "PHPUnit\\Framework\\TestCase"
        ],
        "implements": [],
        "lcom": 4,
        "length": 18,
        "vocabulary": 17,
        "volume": 73.57,
        "difficulty": 0,
        "effort": 0,
        "level": 1.89,
        "bugs": 0.02,
        "time": 0,
        "intelligentContent": 138.97,
        "number_operators": 0,
        "number_operands": 18,
        "number_operators_unique": 0,
        "number_operands_unique": 17,
        "cloc": 17,
        "loc": 41,
        "lloc": 24,
        "mi": 98.69,
        "mIwoC": 56.69,
        "commentWeight": 42.01,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 64,
        "totalStructuralComplexity": 256,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 256,
        "package": "FastForward\\Enum\\Tests\\Calendar\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Tests\\Calendar\\SemesterTest",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "itExposesTheQuartersInsideASemester",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itExposesTheMonthsInsideASemester",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itChecksWhetherAMonthBelongsToASemester",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itResolvesASemesterFromCalendarUnits",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itDescribesSemesters",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "PHPUnit\\Framework\\TestCase",
            "FastForward\\Enum\\Calendar\\Semester",
            "FastForward\\Enum\\Calendar\\Semester"
        ],
        "parents": [
            "PHPUnit\\Framework\\TestCase"
        ],
        "implements": [],
        "lcom": 5,
        "length": 1,
        "vocabulary": 1,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 1,
        "number_operators_unique": 0,
        "number_operands_unique": 1,
        "cloc": 23,
        "loc": 52,
        "lloc": 29,
        "mi": 213.87,
        "mIwoC": 171,
        "commentWeight": 42.87,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 121,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 121,
        "totalStructuralComplexity": 605,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 605,
        "package": "FastForward\\Enum\\Tests\\Calendar\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Tests\\Calendar\\QuarterTest",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "itKeepsCalendarDeclarationOrder",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itExposesTheMonthsInsideAQuarter",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itChecksWhetherAMonthBelongsToAQuarter",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itResolvesAQuarterFromAMonth",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itDescribesQuarters",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "PHPUnit\\Framework\\TestCase",
            "FastForward\\Enum\\Calendar\\Quarter",
            "FastForward\\Enum\\Calendar\\Quarter",
            "FastForward\\Enum\\Calendar\\Quarter"
        ],
        "parents": [
            "PHPUnit\\Framework\\TestCase"
        ],
        "implements": [],
        "lcom": 5,
        "length": 6,
        "vocabulary": 5,
        "volume": 13.93,
        "difficulty": 0,
        "effort": 0,
        "level": 1.67,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 23.22,
        "number_operators": 0,
        "number_operands": 6,
        "number_operators_unique": 0,
        "number_operands_unique": 5,
        "cloc": 22,
        "loc": 49,
        "lloc": 27,
        "mi": 103.7,
        "mIwoC": 60.63,
        "commentWeight": 43.07,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 121,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 121,
        "totalStructuralComplexity": 605,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 605,
        "package": "FastForward\\Enum\\Tests\\Calendar\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Tests\\Comparison\\ComparisonOperatorTest",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "itExposesCompactBackedValues",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itMapsOperatorsToSymbols",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itComparesScalarValues",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itComparesValuesAgainstCandidateSets",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itRejectsInvalidCandidateSets",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itNegatesOperators",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itDescribesOperators",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "PHPUnit\\Framework\\TestCase",
            "FastForward\\Enum\\Comparison\\ComparisonOperator",
            "FastForward\\Enum\\Comparison\\ComparisonOperator",
            "FastForward\\Enum\\Comparison\\ComparisonOperator"
        ],
        "parents": [
            "PHPUnit\\Framework\\TestCase"
        ],
        "implements": [],
        "lcom": 7,
        "length": 51,
        "vocabulary": 31,
        "volume": 252.66,
        "difficulty": 0,
        "effort": 0,
        "level": 1.22,
        "bugs": 0.08,
        "time": 0,
        "intelligentContent": 307.16,
        "number_operators": 0,
        "number_operands": 51,
        "number_operators_unique": 0,
        "number_operands_unique": 31,
        "cloc": 30,
        "loc": 79,
        "lloc": 49,
        "mi": 86.98,
        "mIwoC": 46.17,
        "commentWeight": 40.81,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 144,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 144,
        "totalStructuralComplexity": 1008,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 1008,
        "package": "FastForward\\Enum\\Tests\\Comparison\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "FastForward\\Enum\\Tests\\Trait\\EnumTraitTest",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "itProvidesUnitEnumLookupAndMappingTraits",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itProvidesBackedEnumValueAndOptionTraits",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itProvidesADefaultClassBasedLabelTrait",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itProvidesComparableHelpers",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "itProvidesADefaultDescriptionTrait",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "PHPUnit\\Framework\\TestCase",
            "FastForward\\Enum\\Tests\\Support\\Direction",
            "FastForward\\Enum\\Tests\\Support\\Direction",
            "FastForward\\Enum\\Tests\\Support\\Status",
            "FastForward\\Enum\\Tests\\Support\\Status",
            "FastForward\\Enum\\Tests\\Support\\Status",
            "FastForward\\Enum\\Tests\\Support\\Status",
            "FastForward\\Enum\\Tests\\Support\\Status",
            "FastForward\\Enum\\Tests\\Support\\Status",
            "FastForward\\Enum\\Tests\\Support\\Status",
            "FastForward\\Enum\\Tests\\Support\\Status"
        ],
        "parents": [
            "PHPUnit\\Framework\\TestCase"
        ],
        "implements": [],
        "lcom": 5,
        "length": 21,
        "vocabulary": 9,
        "volume": 66.57,
        "difficulty": 1.25,
        "effort": 83.21,
        "level": 0.8,
        "bugs": 0.02,
        "time": 5,
        "intelligentContent": 53.25,
        "number_operators": 1,
        "number_operands": 20,
        "number_operators_unique": 1,
        "number_operands_unique": 8,
        "cloc": 30,
        "loc": 66,
        "lloc": 36,
        "mi": 96.38,
        "mIwoC": 53.15,
        "commentWeight": 43.23,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 324,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 324,
        "totalStructuralComplexity": 1620,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 1620,
        "package": "FastForward\\Enum\\Tests\\Trait\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "numberOfUnitTests": 0,
        "violations": {}
    }
]